### ISSUE TITLE
Replace container run with `devenv`-command/action in reusable workflow

### ISSUE THREAD

**Issue by gbraad** [gbraad-dotfiles/upstream#110]
https://github.com/gbraad-dotfiles/upstream/blob/5b37bd70aafcea80318471e2455f7778e8ccc3dd/.github/workflows/reusable-tailscale-ssh-container.yml#L84-L98

```yaml
      - name: Run devenv command (zsh)
        run: |
          source ~/.dotfiles/source.sh
          devenv dot${{ inputs.container_name }} system
```

```yaml
      - name: Run devenv command (action)
        uses: gbraad-dotfiles/devenv-action@main
        with:
          prefix: dot${{ inputs.container_name }}
          command: system
```

**Comment by gbraad** [comment]
Replace other commands with zsh-action or devenv action

```yaml
    - name: Run devenv command
      uses: gbraad-dotfiles/devenv-action@main
      with:
        prefix: dotfedora
        command: exec
        args: cat /etc/os-release

    - name: Wait until ready
      uses: gbraad-actions/zsh-action@main
      with:
        run: |
          until devenv dotfedora exec systemctl is-active --quiet tailscaled
          do
            sleep 1
          done
```
