### ISSUE TITLE
Actions in case of failure during build process

### ISSUE THREAD

**Issue by gbraad** [gbraad-dotfiles/upstream#70]
Consider adding:
```yaml
      - name: Install dotfiles action
        if: failure()
        uses: gbraad-dotfiles/install-dotfiles@v1
      - name: Tailscale
        if: failure()
        uses: spotsnel-actions/tailscale-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: --ssh --accept-dns=false --operator=runner
          hostname: dotfiles
      - name: Hang around
        if: failure()
        run: |
          sleep infinity
```
