### ISSUE TITLE
Use re-usable workflows

### ISSUE THREAD

**Issue by gbraad** [gbraad-dotfiles/upstream#90]
```yaml
  - include: ./workflow
    with:
      - base_image: ${{ env.BASE_IMAGE }}
      - base_version: ${{ env.BASE_VERSION }}
```
